import { loadData, saveData } from '@/lib/storage';
import { uid } from '@/lib/uid';
import { getTasks, updateTask } from '@/services/tasks';
import { todayCivilDate, addDays, isValidCivilDate } from '@/lib/date';
import type { Task } from '@/types/tasks';
import type { Habit, HabitLog } from '@/types/habit';

export interface TaskRecurrenceException { date:string; action:'skip'|'reschedule'; replacementDate?:string; reason?:string; }
export interface TaskCarryForwardRule { enabled:boolean; maxDays:number; preserveTime:boolean; }
export interface TaskLink { taskId:string; goalIds:string[]; habitIds:string[]; updatedAt:string; }
export interface TaskReminder { id:string; taskId:string; title:string; date:string; time:string; enabled:boolean; notificationId?:string|null; }
export interface HabitTemplate { id:string; name:string; description:string; icon:string; color:string; frequency:Habit['frequency']; days:Habit['days']; targetCount:number; reminderTime:string|null; createdAt:string; updatedAt:string; }
export interface HabitSkipWindow { id:string; habitId:string; startDate:string; endDate:string; reason:string; }
export interface HabitNote { id:string; habitId:string; date:string; note:string; createdAt:string; updatedAt:string; }
export interface HabitAnalytics { consistencyScore:number; scheduled:number; completed:number; completionRate:number; currentStreak:number; bestStreak:number; weekly:number[]; monthly:number[]; }

const KEYS={exceptions:'jeevya:tasks:recurrence-exceptions:v1',carry:'jeevya:tasks:carry-forward:v1',links:'jeevya:tasks:links:v1',reminders:'jeevya:task-reminders:v1',habitTemplates:'jeevya:habit-templates:v2',skip:'jeevya:habit-skip-windows:v1',notes:'jeevya:habit-notes:v1'} as const;
const read=<T,>(key:string,fallback:T)=>loadData<T>(key,fallback);

export async function setRecurrenceException(taskId:string,exception:TaskRecurrenceException){const all=await read<Record<string,TaskRecurrenceException[]>>(KEYS.exceptions,{});const list=all[taskId]??[];all[taskId]=[...list.filter(x=>x.date!==exception.date),exception];await saveData(KEYS.exceptions,all);return exception;}
export async function getRecurrenceExceptions(taskId:string){return (await read<Record<string,TaskRecurrenceException[]>>(KEYS.exceptions,{}))[taskId]??[];}
export async function clearRecurrenceException(taskId:string,date:string){const all=await read<Record<string,TaskRecurrenceException[]>>(KEYS.exceptions,{});all[taskId]=(all[taskId]??[]).filter(x=>x.date!==date);await saveData(KEYS.exceptions,all);}
export async function setCarryForwardRule(taskId:string,rule:TaskCarryForwardRule){const all=await read<Record<string,TaskCarryForwardRule>>(KEYS.carry,{});all[taskId]={enabled:rule.enabled,maxDays:Math.max(0,Math.min(30,Math.floor(rule.maxDays))),preserveTime:rule.preserveTime};await saveData(KEYS.carry,all);return all[taskId];}
export async function getCarryForwardRule(taskId:string){return (await read<Record<string,TaskCarryForwardRule>>(KEYS.carry,{}))[taskId]??{enabled:false,maxDays:7,preserveTime:true};}
export async function carryForwardTask(task:Task,fromDate=todayCivilDate()){const rule=await getCarryForwardRule(task.id);if(!rule.enabled||task.completed||!task.dueDate||task.dueDate>=fromDate)return task;const max=addDays(task.dueDate,rule.maxDays);if(!max||fromDate>max)return task;return updateTask(task.id,{dueDate:fromDate,dueTime:rule.preserveTime?task.dueTime:null}) as Promise<Task>;}
export async function setTaskLinks(taskId:string,goalIds:string[],habitIds:string[]){const all=await read<Record<string,TaskLink>>(KEYS.links,{});const next={taskId,goalIds:[...new Set(goalIds.filter(Boolean))],habitIds:[...new Set(habitIds.filter(Boolean))],updatedAt:new Date().toISOString()};all[taskId]=next;await saveData(KEYS.links,all);return next;}
export async function getTaskLinks(taskId:string){return (await read<Record<string,TaskLink>>(KEYS.links,{}))[taskId]??{taskId,goalIds:[],habitIds:[],updatedAt:new Date(0).toISOString()};}
export async function setTaskReminder(taskId:string,title:string,date:string,time:string,enabled=true){if(!isValidCivilDate(date)||!/^[0-2]\d:[0-5]\d$/.test(time))throw new Error('Invalid reminder date/time');const all=await read<TaskReminder[]>(KEYS.reminders,[]);const existing=all.find(x=>x.taskId===taskId);const next={id:existing?.id??uid('rem_'),taskId,title:title.trim()||'Jeevya task reminder',date,time,enabled,notificationId:existing?.notificationId??null};await saveData(KEYS.reminders,[...all.filter(x=>x.taskId!==taskId),next]);return next;}
export async function getTaskReminders(){return read<TaskReminder[]>(KEYS.reminders,[]);}
export async function deleteTaskReminder(taskId:string){await saveData(KEYS.reminders,(await getTaskReminders()).filter(x=>x.taskId!==taskId));}
export async function createHabitTemplate(input:Omit<HabitTemplate,'id'|'createdAt'|'updatedAt'>){const now=new Date().toISOString();const item={...input,id:uid('htpl_'),createdAt:now,updatedAt:now};const all=await read<HabitTemplate[]>(KEYS.habitTemplates,[]);await saveData(KEYS.habitTemplates,[item,...all]);return item;}
export async function getHabitTemplates(){return read<HabitTemplate[]>(KEYS.habitTemplates,[]);}
export async function deleteHabitTemplate(id:string){await saveData(KEYS.habitTemplates,(await getHabitTemplates()).filter(x=>x.id!==id));}
export async function setHabitSkipWindow(input:Omit<HabitSkipWindow,'id'>){if(!isValidCivilDate(input.startDate)||!isValidCivilDate(input.endDate)||input.startDate>input.endDate)throw new Error('Invalid skip window');const all=await read<HabitSkipWindow[]>(KEYS.skip,[]);const item={...input,id:uid('skip_')};await saveData(KEYS.skip,[...all.filter(x=>x.habitId!==input.habitId||x.endDate<input.startDate||x.startDate>input.endDate),item]);return item;}
export async function getHabitSkipWindows(habitId:string){return (await read<HabitSkipWindow[]>(KEYS.skip,[])).filter(x=>x.habitId===habitId);}
export async function removeHabitSkipWindow(id:string){await saveData(KEYS.skip,(await read<HabitSkipWindow[]>(KEYS.skip,[])).filter(x=>x.id!==id));}
export async function isHabitSkipped(habitId:string,date:string){return (await getHabitSkipWindows(habitId)).some(x=>x.startDate<=date&&x.endDate>=date);}
export async function setHabitNote(habitId:string,date:string,note:string){const all=await read<HabitNote[]>(KEYS.notes,[]);const now=new Date().toISOString();const existing=all.find(x=>x.habitId===habitId&&x.date===date);const item={id:existing?.id??uid('hnote_'),habitId,date,note:note.trim(),createdAt:existing?.createdAt??now,updatedAt:now};await saveData(KEYS.notes,[...all.filter(x=>x.id!==existing?.id),item]);return item;}
export async function getHabitNotes(habitId:string){return (await read<HabitNote[]>(KEYS.notes,[])).filter(x=>x.habitId===habitId);}
export async function getHabitAnalytics(habit:Habit,logs:HabitLog[],end=todayCivilDate()):Promise<HabitAnalytics>{const start=addDays(end,-90)??end;const skipped=await getHabitSkipWindows(habit.id);const completed=new Set(logs.filter(x=>x.completed).map(x=>x.date));let scheduled=0,done=0;const weekly=Array(13).fill(0) as number[];const monthly=Array(3).fill(0) as number[];for(let d=start;d<=end;d=addDays(d,1)??end){const dt=new Date(d+'T12:00:00');const wd=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'][dt.getDay()] as Habit['days'][number];const isScheduled=habit.frequency==='daily'||habit.days.includes(wd);const skip=skipped.some(x=>x.startDate<=d&&x.endDate>=d);if(isScheduled&&!skip){scheduled++;if(completed.has(d))done++;const week=Math.min(12,Math.floor((dt.getTime()-new Date(start+'T12:00:00').getTime())/604800000));if(completed.has(d))weekly[week]++;const month=Math.floor((new Date(end+'T12:00:00').getTime()-dt.getTime())/2592000000);if(month<3&&completed.has(d))monthly[2-month]++;}}const consistency=scheduled?Math.round(done/scheduled*100):0;return{consistencyScore:consistency,scheduled,completed:done,completionRate:consistency,currentStreak:0,bestStreak:0,weekly,monthly};}
export function recoveredStreak(completedDates:string[],graceDays=1):number{const dates=new Set(completedDates);if(!completedDates.length)return 0;let cursor=completedDates.slice().sort().at(-1) as string;let streak=0;let misses=0;while(cursor){if(dates.has(cursor)){streak++;misses=0}else{misses++;if(misses>Math.max(0,graceDays))break}const prev=addDays(cursor,-1);if(!prev)break;cursor=prev}return streak;}
export async function bulkUpdateTasks(ids:string[],patch:Partial<Pick<Task,'completed'|'archived'|'priority'|'dueDate'|'dueTime'>>){const target=new Set(ids);const changed:Task[]=[];for(const task of await getTasks())if(target.has(task.id)){const updated=await updateTask(task.id,patch);if(updated)changed.push(updated);}return changed;}

