import { loadData, saveData } from '@/lib/storage';
import { getWorkoutHistory, getWorkoutSessions, getWorkout } from '@/services/workouts';
import { getExercisesByIds, getExercises } from '@/services/exercises';
import type { Workout, WorkoutExercise, WorkoutSession, WorkoutSet } from '@/types/workout';

export interface RestTimerState { workoutId: string; endsAt: number; durationSeconds: number; pausedRemainingSeconds?: number; }
export interface WorkoutBlock { id:string; type:'warmup'|'main'|'cooldown'; label:string; durationMinutes?:number; exerciseIds:string[]; }
export interface ExerciseGrouping { exerciseId:string; groupId:string|null; mode:'single'|'superset'|'circuit'; }
export interface ProgressiveSuggestion { exerciseId:string; action:'increase_weight'|'increase_reps'|'hold'|'reduce'; message:string; suggestedWeightKg:number|null; suggestedReps:number|null; confidence:'high'|'medium'|'low'; }
export interface WorkoutAdherenceAnalytics { periodDays:number; scheduledWorkouts:number; completedWorkouts:number; adherencePercent:number|null; activeDays:number; averageDaysBetweenWorkouts:number|null; longestGapDays:number; consistencyByWeek:{week:string;completed:number;scheduled:number}[]; }
export interface MuscleBalanceRow { muscle:string; sets:number; sharePercent:number; }
export interface WorkoutAdvancedAnalytics { volumeTrend:{date:string;volume:number}[]; prTimeline:{date:string;exerciseId:string;recordType:string;value:number}[]; muscleBalance:MuscleBalanceRow[]; adherence:WorkoutAdherenceAnalytics; }
const REST_KEY='jeevya:workout:rest-timer:v2'; const RECOVERY_KEY='jeevya:workout:recovery:v2'; const BLOCK_KEY='jeevya:workout:blocks:v1'; const GROUP_KEY='jeevya:workout:groups:v1';

export async function saveRestTimerState(state:RestTimerState|null){await saveData(REST_KEY,state)} export async function getRestTimerState(){return loadData<RestTimerState|null>(REST_KEY,null)} export async function clearRestTimerState(){await saveData(REST_KEY,null)}
export async function saveWorkoutRecovery(workoutId:string,state:{savedAt:string;currentExerciseIndex:number;elapsedSeconds:number;paused:boolean}){const all=await loadData<Record<string,unknown>>(RECOVERY_KEY,{});all[workoutId]=state;await saveData(RECOVERY_KEY,all)}
export async function getWorkoutRecovery(workoutId:string){const all=await loadData<Record<string,any>>(RECOVERY_KEY,{});return all[workoutId]??null}
export async function clearWorkoutRecovery(workoutId:string){const all=await loadData<Record<string,unknown>>(RECOVERY_KEY,{});delete all[workoutId];await saveData(RECOVERY_KEY,all)}
export async function getWorkoutBlocks(workoutId:string){const all=await loadData<Record<string,WorkoutBlock[]>>(BLOCK_KEY,{});return all[workoutId]??[]}
export async function saveWorkoutBlocks(workoutId:string,blocks:WorkoutBlock[]){const all=await loadData<Record<string,WorkoutBlock[]>>(BLOCK_KEY,{});all[workoutId]=blocks;await saveData(BLOCK_KEY,all);return blocks}
export async function getExerciseGroupings(workoutId:string){const all=await loadData<Record<string,ExerciseGrouping[]>>(GROUP_KEY,{});return all[workoutId]??[]}
export async function saveExerciseGroupings(workoutId:string,groups:ExerciseGrouping[]){const all=await loadData<Record<string,ExerciseGrouping[]>>(GROUP_KEY,{});all[workoutId]=groups;await saveData(GROUP_KEY,all);return groups}

function kg(s:WorkoutSet){const n=s.weightKg??s.weight;return Number.isFinite(n??NaN)&&(n??0)>0?n!:null} function reps(s:WorkoutSet){return Number.isFinite(s.reps??NaN)&&(s.reps??0)>0?s.reps!:null}
export function suggestProgressiveOverload(current:WorkoutSet[],previous:WorkoutSet[]):ProgressiveSuggestion{const c=current.filter(s=>s.completed),p=previous.filter(s=>s.completed);if(!c.length||!p.length)return{exerciseId:'',action:'hold',message:'Complete enough sets to establish a progression baseline.',suggestedWeightKg:null,suggestedReps:null,confidence:'low'};const ca=c.reduce((n,s)=>n+(reps(s)??0),0)/c.length,pa=p.reduce((n,s)=>n+(reps(s)??0),0)/p.length,cw=c.map(kg).filter((x):x is number=>x!=null).at(-1)??null,pw=p.map(kg).filter((x):x is number=>x!=null).at(-1)??null;if(cw!=null&&pw!=null&&ca>=pa+1)return{exerciseId:'',action:'increase_weight',message:'Reps improved versus the previous performance. Consider a small load increase while preserving form.',suggestedWeightKg:Math.round((cw+Math.max(.5,cw*.025))*10)/10,suggestedReps:Math.round(pa),confidence:'high'};if(cw!=null&&pw!=null&&cw>=pw&&ca<pa-2)return{exerciseId:'',action:'reduce',message:'Performance is below the previous session. Hold or slightly reduce load and rebuild reps.',suggestedWeightKg:Math.round(cw*.975*10)/10,suggestedReps:Math.round(pa),confidence:'medium'};return{exerciseId:'',action:'hold',message:'Hold the current load and improve reps or execution before progressing.',suggestedWeightKg:cw,suggestedReps:Math.round(Math.max(ca,pa)),confidence:'medium'}}
export async function getProgressiveOverloadSuggestions(workoutId:string){const w=await getWorkout(workoutId);if(!w)return[];const sessions=await getWorkoutSessions();return Promise.all(w.exercises.map(async e=>{const prevSessions=sessions.filter(s=>s.status==='completed'&&s.exercises.some(x=>x.exerciseId===e.exerciseId)).sort((a,b)=>Date.parse(b.completedAt??b.createdAt)-Date.parse(a.completedAt??a.createdAt));const prev=prevSessions[0]?.exercises.find(x=>x.exerciseId===e.exerciseId)?.sets??[];const s=suggestProgressiveOverload(e.sets,prev);s.exerciseId=e.exerciseId;return s}))}
export async function substituteExercises(exerciseId:string,limit=8){const map=await getExercisesByIds([exerciseId]);const source=map.get(exerciseId);if(!source)return[];const page=await getExercises({page:0,pageSize:100,filter:{body_part:source.body_part??undefined,equipment:source.equipment??undefined}});return page.data.filter(e=>e.id!==exerciseId).slice(0,limit)}
function weekKey(date:string){const d=new Date(date+'T00:00:00');const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toISOString().slice(0,10)}
export async function getWorkoutAdherenceAnalytics(periodDays=90):Promise<WorkoutAdherenceAnalytics>{const sessions=await getWorkoutHistory();const end=new Date();const start=new Date(end);start.setDate(end.getDate()-periodDays+1);const recent=sessions.filter(s=>new Date(s.completedAt??s.createdAt)>=start);const dates=[...new Set(recent.map(s=>(s.completedAt??s.createdAt).slice(0,10)))].sort();let longest=0,last:number|null=null;for(const d of dates){const t=Date.parse(d);if(last!=null)longest=Math.max(longest,Math.round((t-last)/86400000)-1);last=t}const gaps=dates.slice(1).map((d,i)=>Math.round((Date.parse(d)-Date.parse(dates[i]))/86400000));const weeks=new Map<string,number>();dates.forEach(d=>weeks.set(weekKey(d),(weeks.get(weekKey(d))??0)+1));return{periodDays,scheduledWorkouts:0,completedWorkouts:recent.length,adherencePercent:null,activeDays:dates.length,averageDaysBetweenWorkouts:gaps.length?gaps.reduce((a,b)=>a+b,0)/gaps.length:null,longestGapDays:longest,consistencyByWeek:[...weeks.entries()].sort().map(([week,completed])=>({week,completed,scheduled:0}))}}
export async function getWorkoutAdvancedAnalytics(periodDays=90):Promise<WorkoutAdvancedAnalytics>{const sessions=await getWorkoutHistory(),cutoff=Date.now()-periodDays*86400000,recent=sessions.filter(s=>Date.parse(s.completedAt??s.createdAt)>=cutoff),volumeTrend=new Map<string,number>(),muscleCounts=new Map<string,number>(),ids=[...new Set(recent.flatMap(s=>s.exercises.map(e=>e.exerciseId)))],metas=await getExercisesByIds(ids),prTimeline:WorkoutAdvancedAnalytics['prTimeline']=[],best=new Map<string,number>();for(const s of recent){const date=(s.completedAt??s.createdAt).slice(0,10);let volume=0;for(const e of s.exercises){const muscle=metas.get(e.exerciseId)?.muscle_group??metas.get(e.exerciseId)?.body_part??'Unspecified',sets=e.sets.filter(x=>x.completed);muscleCounts.set(muscle,(muscleCounts.get(muscle)??0)+sets.length);for(const set of sets){const w=kg(set),r=reps(set);if(w&&r)volume+=w*r;if(w){const key=e.exerciseId+':weight';if(w>(best.get(key)??0)){best.set(key,w);prTimeline.push({date,exerciseId:e.exerciseId,recordType:'max_weight',value:w})}}}}volumeTrend.set(date,(volumeTrend.get(date)??0)+volume)}const total=[...muscleCounts.values()].reduce((a,b)=>a+b,0)||1;return{volumeTrend:[...volumeTrend].sort().map(([date,volume])=>({date,volume})),prTimeline:prTimeline.sort((a,b)=>a.date.localeCompare(b.date)),muscleBalance:[...muscleCounts].sort((a,b)=>b[1]-a[1]).map(([muscle,sets])=>({muscle,sets,sharePercent:Math.round(sets/total*100)})),adherence:await getWorkoutAdherenceAnalytics(periodDays)}}
export function inferRpeFromRir(rir:number|null|undefined){return rir==null?null:Math.max(1,Math.min(10,10-rir))}
export function inferRirFromRpe(rpe:number|null|undefined){return rpe==null?null:Math.max(0,Math.min(9,10-rpe))}
