import { useEffect, useState } from 'react';
import { Pressable, ScrollView, TextInput, View, Alert } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import * as DocumentPicker from 'expo-document-picker';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { useRouter } from 'expo-router';
import { ArrowLeft, CalendarDays, Lock, Search, Sparkles } from 'lucide-react-native';
import { Button, ButtonText } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Heading } from '@/components/ui/heading';
import { Text } from '@/components/ui/text';
import { getEntries } from '@/services/journal';
import { getJournalHeatmap, getJournalMeta, getJournalSettings, generateWeeklyReflectionPrompt, saveJournalMeta, saveJournalSettings, searchJournal, summarizeJournalWithOptIn } from '@/services/readingJournalAdvanced';
import type { JournalEntry } from '@/types/journal';

export default function AdvancedJournal(){
 const router=useRouter();const[entries,setEntries]=useState<JournalEntry[]>([]),[results,setResults]=useState<JournalEntry[]>([]),[q,setQ]=useState('');
 const[selected,setSelected]=useState<JournalEntry|null>(null),[energy,setEnergy]=useState(''),[gratitude,setGratitude]=useState(''),[privateOnly,setPrivateOnly]=useState(true),[aiOptIn,setAiOptIn]=useState(false),[prompt,setPrompt]=useState(''),[attachmentCount,setAttachmentCount]=useState(0),[linkDomain,setLinkDomain]=useState<'tasks'|'goals'|'workout'>('goals'),[linkId,setLinkId]=useState('');
 const[heat,setHeat]=useState<Array<{date:string;entries:number;mood:number|null;energy:number|null}>>([]);
 const load=async()=>{const es=await getEntries();setEntries(es);setResults(es);const s=await getJournalSettings();setPrivateOnly(s.privateOnly);setAiOptIn(s.aiSummaryOptIn);setPrompt(await generateWeeklyReflectionPrompt());const end=new Date().toISOString().slice(0,10);const d=new Date();d.setUTCDate(d.getUTCDate()-29);setHeat(await getJournalHeatmap(d.toISOString().slice(0,10),end));};
 useEffect(()=>{void load()},[]);
 const choose=async(e:JournalEntry)=>{setSelected(e);const m=await getJournalMeta(e.id);setEnergy(m.energy?.toString()??'');setGratitude(m.gratitude.join('\n'));setAttachmentCount(m.attachments.length);};
 const saveMeta=async()=>{if(!selected)return;const current=await getJournalMeta(selected.id);await saveJournalMeta({journalId:selected.id,energy:energy?Number(energy):null,gratitude:gratitude.split('\n').map(x=>x.trim()).filter(Boolean),attachments:current.attachments,privateOnly});setAttachmentCount(current.attachments.length);};
 const addAttachment=async()=>{if(!selected)return;const image=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.85});if(!image.canceled&&image.assets[0]){const current=await getJournalMeta(selected.id);await saveJournalMeta({...current,attachments:[...current.attachments,{id:Date.now().toString(),uri:image.assets[0].uri,name:image.assets[0].fileName??'image',mimeType:image.assets[0].mimeType??'image/*'}]});setAttachmentCount(current.attachments.length+1);return;}const picked=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true,multiple:false});if(!picked.canceled){const file=picked.assets[0];const current=await getJournalMeta(selected.id);await saveJournalMeta({...current,attachments:[...current.attachments,{id:Date.now().toString(),uri:file.uri,name:file.name,mimeType:file.mimeType}]});setAttachmentCount(current.attachments.length+1);}};
 const addLink=async()=>{if(selected&&linkId.trim()){const {saveJournalLink}=await import('@/services/readingJournalAdvanced');await saveJournalLink({journalId:selected.id,domain:linkDomain,recordId:linkId.trim()});Alert.alert('Linked','Journal entry linked to '+linkDomain);setLinkId('');}};
 const exportJournal=async()=>{const {exportJournalJSON}=await import('@/services/readingJournalAdvanced');const uri=(FileSystem.cacheDirectory??'')+'jeevya-journal-'+Date.now()+'.json';await FileSystem.writeAsStringAsync(uri,await exportJournalJSON());if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'application/json',dialogTitle:'Export journal'});};
 const search=async(v:string)=>{setQ(v);setResults(v?await searchJournal(v):entries)};
 return <ScrollView className="flex-1 bg-background" contentContainerStyle={{paddingBottom:40}}><View className="gap-4 px-5 pt-14">
  <View className="flex-row items-center gap-3"><Button variant="ghost" size="icon" onPress={()=>router.back()}><ArrowLeft size={20}/></Button><View className="flex-1"><Text size="sm" className="text-muted-foreground">Journal</Text><Heading size="xl">Advanced Journal</Heading></View></View>
  <Card className="gap-3 p-4"><View className="flex-row items-center gap-2"><Lock size={18}/><Heading size="sm">Private/local-only mode</Heading></View><Text size="sm" className="text-muted-foreground">Journal stays local unless you explicitly enable an AI summary request.</Text><Button variant="outline" onPress={()=>{const next=!privateOnly;setPrivateOnly(next);void saveJournalSettings({privateOnly:next})}}><ButtonText>{privateOnly?'Local-only enabled':'Local-only disabled'}</ButtonText></Button></Card>
  <Card className="gap-3 p-4"><View className="flex-row items-center gap-2"><Search size={17}/><TextInput value={q} onChangeText={search} placeholder="Search journal" placeholderTextColor="#9CA3AF" className="flex-1 text-foreground"/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:6}}>{['great','good','okay','bad','awful'].map(m=><Pressable key={m} className="rounded-full border border-border px-3 py-2" onPress={()=>void searchJournal('',{mood:m as JournalEntry['mood']}).then(setResults)}><Text size="xs">{m}</Text></Pressable>)}</ScrollView></Card>
  <Card className="p-4"><Heading size="md">Weekly reflection</Heading><Text size="sm" className="mt-2 text-muted-foreground">{prompt}</Text></Card>
  <Card className="p-4"><View className="flex-row items-center gap-2"><CalendarDays size={18}/><Heading size="md">30-day calendar heatmap</Heading></View><View className="mt-3 flex-row flex-wrap gap-1">{heat.map(x=><View key={x.date} className={x.entries?'h-7 w-7 rounded-md items-center justify-center bg-primary/30':'h-7 w-7 rounded-md items-center justify-center bg-muted'}><Text size="xs">{x.entries||''}</Text></View>)}</View></Card>
  {results.map(e=><Pressable key={e.id} onPress={()=>void choose(e)}><Card className={selected?.id===e.id?'border-primary p-4':'p-4'}><Text className="font-semibold">{e.title||'Untitled entry'}</Text><Text size="xs" className="text-muted-foreground">{e.date} · {e.mood??'No mood'}</Text><Text size="sm" className="mt-2" numberOfLines={3}>{e.content}</Text></Card></Pressable>)}
  {selected?<Card className="gap-3 p-4"><Heading size="md">Entry signals</Heading><TextInput value={energy} onChangeText={setEnergy} keyboardType="number-pad" placeholder="Energy 1-10" className="rounded-xl border border-border p-3 text-foreground"/><TextInput value={gratitude} onChangeText={setGratitude} multiline placeholder="Gratitude, one item per line" className="min-h-24 rounded-xl border border-border p-3 text-foreground"/><View className="flex-row gap-2"><Button className="flex-1" onPress={()=>void saveMeta()}><ButtonText>Save signals</ButtonText></Button><Button variant="outline" className="flex-1" onPress={()=>void addAttachment()}><ButtonText>Attach ({attachmentCount})</ButtonText></Button></View><Button variant="outline" onPress={()=>void exportJournal()}><ButtonText>Export journal</ButtonText></Button><View className="flex-row gap-2">{(['tasks','goals','workout'] as const).map(d=><Pressable key={d} onPress={()=>setLinkDomain(d)} className={linkDomain===d?'rounded-full bg-primary px-3 py-2':'rounded-full bg-muted px-3 py-2'}><Text size="xs" className={linkDomain===d?'text-primary-foreground':''}>{d}</Text></Pressable>)}</View><View className="flex-row gap-2"><TextInput value={linkId} onChangeText={setLinkId} placeholder="Record ID" className="flex-1 rounded-xl border border-border p-3 text-foreground"/><Button variant="outline" onPress={()=>void addLink()}><ButtonText>Link</ButtonText></Button></View><Button variant="outline" onPress={()=>{const next=!aiOptIn;setAiOptIn(next);void saveJournalSettings({aiSummaryOptIn:next})}}><Sparkles size={16}/><ButtonText>{aiOptIn?'AI summary opt-in enabled':'Enable AI summary opt-in'}</ButtonText></Button>{aiOptIn?<Button variant="outline" onPress={()=>void summarizeJournalWithOptIn(selected.id).then(s=>Alert.alert('AI summary',s)).catch(e=>Alert.alert('Summary unavailable',e instanceof Error?e.message:String(e)))}><ButtonText>Summarize with configured AI</ButtonText></Button>:null}</Card>:null}
 </View></ScrollView>;
}