import { useEffect, useState } from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import { useRouter } from 'expo-router';
import { AlertTriangle, ArrowLeft, Link2, Target, CalendarCheck } from 'lucide-react-native';
import { Button, ButtonText } from '@/components/ui/button'; import { Card } from '@/components/ui/card'; import { Heading } from '@/components/ui/heading'; import { Text } from '@/components/ui/text';
import { getUnifiedGoals, linkGoalRecord, getGoalStatusLabel } from '@/services/goalsIntegration'; import { getTasks } from '@/services/tasks'; import { getHabits } from '@/services/habits'; import { getBooks } from '@/services/books'; import { getEntries } from '@/services/journal'; import { getSavingsGoals } from '@/services/finance'; import { getWorkoutHistory } from '@/services/workouts'; import { getFoodLogs } from '@/services/nutrition'; import type { UnifiedGoal } from '@/types/goalsIntegration';

export default function AdvancedGoals(){
 const router=useRouter();const[goals,setGoals]=useState<UnifiedGoal[]>([]),[tasks,setTasks]=useState<any[]>([]),[habits,setHabits]=useState<any[]>([]),[books,setBooks]=useState<any[]>([]),[journal,setJournal]=useState<any[]>([]),[finance,setFinance]=useState<any[]>([]),[health,setHealth]=useState<any[]>([]),[nutrition,setNutrition]=useState<any[]>([]);
 const load=async()=>{const[g,t,h,b,j,f,w,n]=await Promise.all([getUnifiedGoals(),getTasks(),getHabits(),getBooks(),getEntries(),getSavingsGoals(),getWorkoutHistory(),getFoodLogs()]);setGoals(g);setTasks(t);setHabits(h);setBooks(b);setJournal(j);setFinance(f);setHealth(w);setNutrition(n)};useEffect(()=>{void load()},[]);
 const addLink=async(g:UnifiedGoal,domain:'tasks'|'habits'|'books'|'journal'|'finance'|'health'|'nutrition',id:string)=>{if(g.id.includes(':'))return;await linkGoalRecord(g.id,domain,id);await load()};
 const candidates=(g:UnifiedGoal)=>g.id.includes(':')?[]:([{domain:'tasks',rows:tasks},{domain:'habits',rows:habits},{domain:'books',rows:books},{domain:'journal',rows:journal},{domain:'finance',rows:finance},{domain:'health',rows:health},{domain:'nutrition',rows:nutrition}] as const).flatMap(x=>x.rows.slice(0,3).map(r=>({domain:x.domain,id:r.id,label:r.title??r.name??r.description??r.content?.slice(0,30)??r.id}))).filter(x=>!(g.linkedRecordIds??[]).includes(x.id)).slice(0,10);
 return <ScrollView className="flex-1 bg-background" contentContainerStyle={{paddingBottom:40}}><View className="gap-4 px-5 pt-14">
  <View className="flex-row items-center gap-3"><Button variant="ghost" size="icon" onPress={()=>router.back()}><ArrowLeft size={20}/></Button><View className="flex-1"><Text size="sm" className="text-muted-foreground">Goals</Text><Heading size="xl">Goal Command Center</Heading></View></View>
  <View className="flex-row gap-2"><Button className="flex-1" onPress={()=>router.push('/goals/create')}><ButtonText>Create</ButtonText></Button><Button variant="outline" className="flex-1" onPress={()=>router.push('/goals/review' as never)}><ButtonText>Weekly Review</ButtonText></Button></View>
  {goals.map(g=><Card key={g.id} className="gap-3 p-4"><View className="flex-row items-center gap-2"><Target size={18}/><View className="flex-1"><Heading size="sm">{g.title}</Heading><Text size="xs" className="text-muted-foreground">{getGoalStatusLabel(g.status)} Â· {g.progressPercentage??0}%</Text></View>{g.status==='behind'?<AlertTriangle size={18}/>:null}</View><Text size="sm" className="text-muted-foreground">Linked records: {g.linkedRecordIds?.length??0}</Text>{candidates(g).map(c=><Pressable key={c.domain+c.id} onPress={()=>void addLink(g,c.domain,c.id)} className="rounded-xl bg-muted p-3"><View className="flex-row items-center gap-2"><Link2 size={14}/><Text size="xs">{c.domain}: {c.label}</Text></View></Pressable>)}</Card>)}
 </View></ScrollView>;
}
