// JEEVYA 3T.6: authentication identity + sync lifecycle safety.
// @ts-nocheck
import fs from 'node:fs';
const assert = (condition, message) => { if (!condition) throw new Error(message); };
(async () => {
  const memory = new Map();
  Object.defineProperty(globalThis, 'window', { configurable: true, value: { localStorage: { getItem: (key) => memory.get(key) ?? null, setItem: (key, value) => { memory.set(key, value); }, removeItem: (key) => { memory.delete(key); }, clear: () => { memory.clear(); }, get length() { return memory.size; }, key: (index) => Array.from(memory.keys())[index] ?? null } } });
  const AsyncStorage = (await import('@react-native-async-storage/async-storage')).default;
  const { saveData, loadData } = await import('@/lib/storage');
  const { supabase } = await import('@/lib/supabase');
  const { synchronizeJeevya } = await import('@/services/sync');
  await AsyncStorage.clear();
  const originalGetSession = supabase.auth.getSession;
  const originalFrom = supabase.from;
  let sessionUserId = null, remoteRows = [], upserts = [], queriedUsers = [], fromError = null, getSessionSequence = null, selectDelay = 0;
  const setSession = (id) => { sessionUserId = id; getSessionSequence = null; };
  const setSessionSequence = (ids) => { getSessionSequence = [...ids]; };
  Object.defineProperty(supabase.auth, 'getSession', { configurable: true, writable: true, value: async () => { const id = getSessionSequence?.length ? getSessionSequence.shift() : sessionUserId; return { data: { session: id ? { user: { id } } : null }, error: null }; } });
  Object.defineProperty(supabase, 'from', { configurable: true, writable: true, value: () => ({ select: () => ({ eq: async (_field, value) => { assert(typeof value === 'string' && value.trim(), 'remote query must use a concrete session identity'); queriedUsers.push(value); if (selectDelay) await new Promise((resolve) => setTimeout(resolve, selectDelay)); if (fromError) return { data: null, error: fromError }; return { data: remoteRows.filter((row) => row.user_id === value), error: null }; } }), upsert: async (rows) => { upserts.push(...rows); return { data: null, error: null }; } }) });
  let passed = 0;
  const check = async (name, fn) => { try { await fn(); passed++; console.log(`PASS ${name}`); } catch (error) { console.error(`FAIL ${name}: ${error.message}`); throw error; } };
  const task = { id: 'task-3t6', title: 'Identity safety task', completed: false, priority: 'high', dueDate: null, dueTime: null, createdAt: '2026-09-14T08:00:00.000Z', updatedAt: '2026-09-14T08:00:00.000Z', completedAt: null, archived: false, recurrence: null, seriesId: null, subtasks: [], labelIds: [] };
  await check('authenticated sync uses current session user ID', async () => { await AsyncStorage.clear(); await saveData('jeevya:tasks', [task]); setSession('account-a'); remoteRows = []; upserts = []; const result = await synchronizeJeevya(); assert(result.state === 'synced', result.message); assert(upserts.length === 1 && upserts[0].user_id === 'account-a', 'active session identity not used'); });
  await check('guest cannot sync', async () => { setSession(null); upserts = []; const result = await synchronizeJeevya(); assert(result.state === 'auth_required' && upserts.length === 0, 'guest sync was not rejected'); });
  await check('stale cached identity cannot authorize sync', async () => { await AsyncStorage.setItem('jeevya:sync:metadata', JSON.stringify({ version: 1, userId: 'account-a', records: {} })); setSession('account-b'); remoteRows = []; upserts = []; const result = await synchronizeJeevya(); assert(result.state === 'synced', result.message); assert(upserts.every((row) => row.user_id === 'account-b'), 'stale metadata identity used'); });
  await check('Account A syncs only as A', async () => { setSession('account-a'); remoteRows = []; upserts = []; await synchronizeJeevya(); assert(upserts.every((row) => row.user_id === 'account-a'), 'A targeted another identity'); });
  await check('Account B syncs only as B', async () => { setSession('account-b'); remoteRows = []; upserts = []; await synchronizeJeevya(); assert(upserts.every((row) => row.user_id === 'account-b'), 'B reused A identity'); });
  await check('A to signout to B cannot reuse A identity', async () => { setSession('account-a'); remoteRows = []; upserts = []; queriedUsers = []; await synchronizeJeevya(); setSession(null); upserts = []; const signedOut = await synchronizeJeevya(); assert(signedOut.state === 'auth_required' && upserts.length === 0, 'signout did not stop sync'); setSession('account-b'); upserts = []; queriedUsers = []; await synchronizeJeevya(); assert(queriedUsers.every((id) => id === 'account-b'), 'B remote query reused A identity'); assert(upserts.every((row) => row.user_id === 'account-b'), 'B upload reused A identity'); });
  await check('session change during sync is detected', async () => { await AsyncStorage.clear(); await saveData('jeevya:tasks', [task]); remoteRows = []; upserts = []; setSessionSequence(['account-a', 'account-a', 'account-a', 'account-a', 'account-b']); const result = await synchronizeJeevya(); assert(result.state === 'auth_required', `stale session accepted: ${result.message}`); assert(upserts.length === 0, 'stale sync wrote remotely'); assert((await loadData('jeevya:tasks', [])).length === 1, 'stale sync changed local data'); });
  await check('stale sync cannot commit under another user', async () => { await AsyncStorage.clear(); await saveData('jeevya:tasks', [task]); remoteRows = []; upserts = []; setSessionSequence(['account-a', 'account-a', 'account-a', 'account-a', 'account-b']); const result = await synchronizeJeevya(); assert(result.state === 'auth_required' && upserts.length === 0, 'stale operation committed'); });
  await check('concurrent sync remains identity-safe', async () => { await AsyncStorage.clear(); await saveData('jeevya:tasks', [task]); setSession('account-a'); remoteRows = []; upserts = []; selectDelay = 20; const first = synchronizeJeevya(); await new Promise((resolve) => setTimeout(resolve, 2)); setSession('account-b'); const second = synchronizeJeevya(); const [firstResult, secondResult] = await Promise.all([first, second]); assert(firstResult.state === 'auth_required', 'A operation did not stop'); assert(secondResult.state === 'auth_required', 'B inherited A operation'); assert(upserts.length === 0, 'concurrent sync wrote remotely'); selectDelay = 0; });
  await check('malformed sync metadata cannot become identity', async () => { await AsyncStorage.setItem('jeevya:sync:metadata', JSON.stringify({ version: 1, userId: 'forged-user', records: { bad: { fingerprint: 'x' } } })); setSession('account-b'); remoteRows = []; upserts = []; const result = await synchronizeJeevya(); assert(result.state === 'synced', result.message); assert(upserts.every((row) => row.user_id === 'account-b'), 'forged metadata became identity'); });
  await check('missing session fails safely', async () => { setSession(null); upserts = []; const result = await synchronizeJeevya(); assert(result.state === 'auth_required' && upserts.length === 0, 'missing session unsafe'); });
  await check('remote authorization failure preserves local data', async () => { await AsyncStorage.clear(); await saveData('jeevya:tasks', [task]); setSession('account-b'); fromError = new Error('permission denied by RLS'); upserts = []; const before = JSON.stringify(await loadData('jeevya:tasks', [])); const result = await synchronizeJeevya(); const after = JSON.stringify(await loadData('jeevya:tasks', [])); assert(result.state === 'error' && before === after && upserts.length === 0, 'authorization failure mutated local data'); fromError = null; });
  await check('local data remains intact across signout', async () => { await AsyncStorage.clear(); await saveData('jeevya:tasks', [task]); setSession('account-a'); const before = JSON.stringify(await loadData('jeevya:tasks', [])); setSession(null); const result = await synchronizeJeevya(); const after = JSON.stringify(await loadData('jeevya:tasks', [])); assert(result.state === 'auth_required' && before === after, 'signout changed local data'); });
  await check('RLS/client boundary remains unchanged', async () => { const source = fs.readFileSync('src/services/sync.ts', 'utf8'); const sql = fs.readFileSync('sql/jeevya-sync.sql', 'utf8'); assert(source.includes("supabase.from('jeevya_sync_records')"), 'sync client boundary changed'); assert(source.includes(".eq('user_id', sessionUserId)"), 'remote reads are not session-scoped'); assert(source.includes('row.user_id !== sessionUserId'), 'remote write identity guard missing'); assert(!source.includes('SUPABASE_SERVICE_ROLE_KEY'), 'service-role key referenced'); assert(sql.includes('auth.uid() = user_id'), 'RLS ownership policy missing'); });
  await check('3S conflict metadata remains isolated from authentication identity', async () => { const source = fs.readFileSync('src/services/sync.ts', 'utf8'); assert(!source.includes('conflict.userId') && !source.includes('conflict.authUserId'), 'conflict metadata used as auth identity'); assert(source.includes('const conflicts = await getConflicts()'), 'conflict store missing'); });
  Object.defineProperty(supabase.auth, 'getSession', { configurable: true, writable: true, value: originalGetSession }); Object.defineProperty(supabase, 'from', { configurable: true, writable: true, value: originalFrom });
  console.log(`JEEVYA 3T.6 AUTH IDENTITY + SYNC LIFECYCLE SAFETY: ${passed} passed, 0 failed`);
})().catch((error) => { console.error(error); process.exitCode = 1; });

