// @ts-nocheck
import fs from 'node:fs';
const root = process.cwd();
const read = (p: string) => fs.readFileSync(`${root}/${p}`, 'utf8');
const assert = (v: unknown, m: string) => { if (!v) throw new Error(m); };
let passed = 0;
const check = async (name: string, fn: () => void | Promise<void>) => { await fn(); passed++; console.log(`PASS ${name}`); };
async function main() {
  Object.defineProperty(globalThis, 'window', { configurable: true, value: { localStorage: { getItem: () => null, setItem: () => undefined, removeItem: () => undefined } } });
  const { getGlobalChallengeLifecycle, validateGlobalChallenge, isGlobalChallengeMetricCompatible, validateGlobalCommunityAggregate } = await import('@/services/globalData');
  const challenge = { challengeId: 'challenge-1', title: 'Approved challenge', description: 'Aggregate-only challenge', metricName: 'activity', metricType: 'count', targetValue: 10, unit: 'events', startDate: '2026-09-14', endDate: '2026-09-20', geographicLevel: 'global', participantCount: 10, completionCount: 4, dataVersion: 1, schemaVersion: 1, status: 'active' };
  await check('challenge contract is aggregate-only and structurally valid', () => { assert(validateGlobalChallenge(challenge), 'valid challenge rejected'); const types = read('src/types/global.ts'); assert(types.includes('challengeId') && types.includes('participantCount') && types.includes('completionCount'), 'challenge contract missing'); assert(!/participantEmail|participantName|userId|email|journalText|taskText|financialDetails|nutritionDetails|preciseLocation/i.test(types), 'private challenge field found'); });
  await check('challenge lifecycle states are deterministic from dates', () => { assert(getGlobalChallengeLifecycle(challenge, '2026-09-13') === 'upcoming', 'upcoming failed'); assert(getGlobalChallengeLifecycle(challenge, '2026-09-14') === 'active', 'active failed'); assert(getGlobalChallengeLifecycle(challenge, '2026-09-21') === 'completed', 'completed failed'); assert(getGlobalChallengeLifecycle(challenge, 'invalid-date') === 'invalid', 'invalid date failed'); });
  await check('challenge date validation rejects invalid chronology', () => { assert(!validateGlobalChallenge({ ...challenge, startDate: '2026-09-21', endDate: '2026-09-20' }), 'invalid chronology accepted'); assert(!validateGlobalChallenge({ ...challenge, startDate: 'bad' }), 'invalid start date accepted'); });
  await check('challenge metric compatibility is explicit', () => { const metric = { metricName: 'activity', metricType: 'count', period: 'week', periodStart: '2026-09-14', periodEnd: '2026-09-20', aggregateValue: 10, aggregateCount: 10, createdAt: '2026-09-20T00:00:00Z', updatedAt: '2026-09-20T00:00:00Z', dataVersion: 1, schemaVersion: 1 }; assert(isGlobalChallengeMetricCompatible(challenge, metric), 'compatible metric rejected'); assert(!isGlobalChallengeMetricCompatible(challenge, { ...metric, metricType: 'sum' }), 'incompatible metric accepted'); });
  await check('participant counts remain aggregate-only with minimum cohort protection', () => { assert(!validateGlobalChallenge({ ...challenge, participantCount: 4, completionCount: 2 }), 'small cohort accepted'); assert(validateGlobalChallenge({ ...challenge, participantCount: 0, completionCount: 0 }), 'real zero participant state rejected'); assert(!validateGlobalChallenge({ ...challenge, participantCount: 10, completionCount: 11 }), 'completion overflow accepted'); });
  await check('community aggregate contract is privacy-safe', () => { const aggregate = { metricName: 'activity', metricType: 'count', period: 'week', periodStart: '2026-09-14', periodEnd: '2026-09-20', totalParticipants: 10, aggregateActivity: 100, completionRate: 0.5, aggregateTrend: 'up', geographicLevel: 'country', geographicCode: 'IN', dataVersion: 1, schemaVersion: 1 }; assert(validateGlobalCommunityAggregate(aggregate), 'community aggregate rejected'); assert(!validateGlobalCommunityAggregate({ ...aggregate, totalParticipants: 4 }), 'small community cohort accepted'); });
  await check('geography is restricted to approved coarse levels', () => { assert(validateGlobalChallenge({ ...challenge, geographicLevel: 'city', geographicCode: 'DEL' }), 'city geography rejected'); assert(!validateGlobalChallenge({ ...challenge, geographicLevel: 'coordinates' }), 'unsupported geography accepted'); assert(!validateGlobalChallenge({ ...challenge, geographicCode: 'DEL' }), 'code without level accepted'); const types = read('src/types/global.ts'); assert(!/latitude|longitude|coordinates|preciseLocation/i.test(types), 'precise geography found'); });
  await check('unavailable, zero, and insufficient data remain distinct', () => { const service = read('src/services/globalData.ts'); assert(service.includes("status: 'unavailable'"), 'unavailable state missing'); assert(service.includes('participantCount === 0'), 'zero participant state missing'); assert(service.includes("'insufficient_data'"), 'insufficient state missing'); });
  await check('safe participation states exist without enrollment', () => { const types = read('src/types/global.ts'); const service = read('src/services/globalData.ts'); assert(types.includes("'eligible' | 'unavailable' | 'insufficient_data' | 'auth_required' | 'invalid'"), 'participation states missing'); assert(service.includes('getGlobalParticipationStatus'), 'participation status foundation missing'); assert(!/enroll|joinChallenge|addParticipant|insertParticipant/i.test(service), 'enrollment path introduced'); });
  await check('authenticated session remains authoritative for participation access', () => { const service = read('src/services/globalData.ts'); assert(service.includes('supabase.auth.getSession()'), 'session authority missing'); assert(service.includes("return 'auth_required'"), 'auth_required missing'); });
  await check('global layer never reads private domains or sync records', () => { const service = read('src/services/globalData.ts'); for (const table of ['jeevya_sync_records', 'tasks', 'habits', 'books', 'journal', 'finance', 'nutrition', 'workout', 'sleep']) assert(!service.includes(`from('${table}')`), `private table ${table} accessed`); });
  await check('no client trusted global writes or service-role usage exist', () => { const source = `${read('src/services/globalData.ts')}\n${read('src/types/global.ts')}`; assert(!/\.insert\(|\.update\(|\.delete\(/.test(source), 'global client write API found'); assert(!/SUPABASE_SERVICE_ROLE_KEY|service_role|sb_secret/i.test(source), 'service role usage found'); });
  await check('no individual identity, ranking, profile, or social primitives are exposed', () => { const source = `${read('src/types/global.ts')}\n${read('src/services/globalData.ts')}`; assert(!/userRank|userPercentile|leaderboardPosition|individualRank|participantIds|participantList|publicProfile|message|chat|friend|follow/i.test(source), 'individual/social primitive found'); assert(!fs.existsSync(`${root}/src/app/challenges.tsx`), 'challenge UI exposed'); assert(!fs.existsSync(`${root}/src/app/community.tsx`), 'community UI exposed'); });
  await check('3T.9 SQL remains authenticated read-only aggregate authority', () => { const sql = read('sql/jeevya-global-metrics.sql'); assert(sql.includes('enable row level security') && sql.includes('for select') && sql.includes('to authenticated'), '3T.9 RLS missing'); assert(!sql.includes('for insert') && !sql.includes('for update') && !sql.includes('for delete'), 'client write policy added'); assert(sql.includes('aggregate_count >= 5'), 'cohort protection weakened'); });
  await check('3T.10 and 3T.11 foundations remain intact', () => { const service = read('src/services/globalData.ts'); assert(service.includes('readGlobalMetrics') && service.includes('compareGlobalMetric'), '3T.10 statistics foundation missing'); assert(service.includes('compareGlobalPeriods') && service.includes('compareGlobalAggregates') && service.includes('calculateGlobalRankingBand'), '3T.11 foundation missing'); });
  await check('capability boundary remains unchanged and no global UI was added', () => { const capabilities = read('src/types/capabilities.ts'); assert(capabilities.includes('globalStats') && capabilities.includes('leaderboard') && capabilities.includes('community') && capabilities.includes('globalChallenges'), 'capability boundary changed'); assert(!fs.existsSync(`${root}/src/app/leaderboard.tsx`), 'leaderboard UI exposed'); });
  console.log(`JEEVYA 3T.12 GLOBAL CHALLENGES + COMMUNITY FOUNDATION: ${passed} passed, 0 failed`);
}
main().catch((error) => { console.error(error); process.exit(1); });
