import { createProgram,getProgram,listPrograms,updateProgram,deleteProgram,duplicateProgram,activateProgram,deactivateProgram,addScheduleEntry,updateScheduleEntry,removeScheduleEntry,reorderScheduleEntries,getActiveProgram,getScheduledWorkoutsForDate,getScheduledTemplatesForDate,WORKOUT_PROGRAMS_KEY,createWorkoutSessionFromTemplate,getWorkoutTemplate,createWorkoutTemplate,updateWorkoutTemplate,startWorkoutFromTemplate } from '@/services/workoutTemplates';
import { getWorkoutSessions,completeWorkout } from '@/services/workouts';
import { loadData,saveData } from '@/lib/storage';
let passed=0,failed=0; const check=async(n:string,fn:()=>Promise<void>|void)=>{try{await fn();passed++;console.log(`PASS ${passed}. ${n}`)}catch(e){failed++;console.error(`FAIL ${n}:`,e)}};
const assert=(x:unknown,m:string)=>{if(!x)throw new Error(m)};
async function main(){
 await saveData(WORKOUT_PROGRAMS_KEY,[]); const t=await createWorkoutTemplate({name:'Push Template',description:'Upper body'});
 const p=await createProgram({name:'Push Week',description:'Weekly plan'});
 await check('program creation',async()=>assert((await getProgram(p.id))?.name==='Push Week','creation'));
 await check('name trimmed',async()=>assert((await updateProgram(p.id,{name:'  Plan  '})).name==='Plan','trim'));
 await check('description persisted',async()=>assert((await getProgram(p.id))?.description==='Weekly plan','desc'));
 await check('empty name rejected',async()=>{let ok=false;try{await updateProgram(p.id,{name:' '})}catch{ok=true}assert(ok,'validation')});
 const e=await addScheduleEntry(p.id,{dayOfWeek:1,templateId:t.id});
 await check('schedule add',async()=>assert(e.schedule.length===1,'add'));
 await check('weekday stored',async()=>assert(e.schedule[0].dayOfWeek===1,'day'));
 await check('order stored',async()=>assert(e.schedule[0].order===0,'order'));
 await check('enabled default',async()=>assert(e.schedule[0].enabled,'enabled'));
 await check('duplicate schedule rejected',async()=>{let ok=false;try{await addScheduleEntry(p.id,{dayOfWeek:1,templateId:t.id,order:0})}catch{ok=true}assert(ok,'duplicate')});
 const e2=await addScheduleEntry(p.id,{dayOfWeek:1,templateId:'missing-template'});
 await check('missing template retained',async()=>assert(e2.schedule.some(x=>x.templateId==='missing-template'),'missing'));
 await check('invalid day rejected',async()=>{let ok=false;try{await addScheduleEntry(p.id,{dayOfWeek:7,templateId:t.id})}catch{ok=true}assert(ok,'day validation')});
 await check('negative order rejected',async()=>{let ok=false;try{await addScheduleEntry(p.id,{dayOfWeek:2,templateId:t.id,order:-1})}catch{ok=true}assert(ok,'order validation')});
 const moved=await updateScheduleEntry(p.id,e2.schedule[1].id,{dayOfWeek:2,enabled:false});
 await check('schedule update day',async()=>assert(moved.schedule.some(x=>x.dayOfWeek===2),'update day'));
 await check('schedule update enabled',async()=>assert(moved.schedule.some(x=>x.templateId==='missing-template'&&!x.enabled),'update enabled'));
 const removed=await removeScheduleEntry(p.id,e2.schedule[1].id); await check('schedule remove',async()=>assert(!removed.schedule.some(x=>x.templateId==='missing-template'),'remove'));
 await addScheduleEntry(p.id,{dayOfWeek:1,templateId:'a'}); await addScheduleEntry(p.id,{dayOfWeek:1,templateId:'b'}); const list=await getProgram(p.id);
 await check('same weekday multiple entries',async()=>assert(list!.schedule.filter(x=>x.dayOfWeek===1).length===3,'multiple'));
 const first=list!.schedule.find(x=>x.templateId==='a')!; const before=await reorderScheduleEntries(p.id,first.id,1);
 await check('reorder entries',async()=>assert(before.schedule.filter(x=>x.dayOfWeek===1).sort((a,b)=>a.order-b.order).map(x=>x.templateId).includes('a'),'reorder'));
 await check('list programs',async()=>assert((await listPrograms()).length===1,'list'));
 await check('program persistence',async()=>assert((await getProgram(p.id))?.id===p.id,'persist'));
 const dup=await duplicateProgram(p.id);
 await check('duplicate new id',async()=>assert(dup.id!==p.id,'id'));
 await check('duplicate deep schedule ids',async()=>assert(dup.schedule[0]?.id!==list!.schedule[0]?.id,'deep'));
 await check('duplicate inactive',async()=>assert(!dup.isActive,'inactive duplicate'));
 await activateProgram(p.id); await check('activation',async()=>assert((await getActiveProgram())?.id===p.id,'active'));
 await activateProgram(dup.id); await check('exclusive activation',async()=>{const xs=await listPrograms();assert(xs.filter(x=>x.isActive).length===1,'exclusive');assert(xs.find(x=>x.id===dup.id)?.isActive,'new active')});
 await deactivateProgram(dup.id); await check('deactivation',async()=>assert((await getActiveProgram())===null,'deactivate'));
 await activateProgram(p.id); const date=new Date(2026,8,14); const scheduled=await getScheduledWorkoutsForDate(date); await check('weekday resolution',async()=>assert(scheduled.every(x=>x.dayOfWeek===1),'weekday'));
 await check('disabled filtered',async()=>assert(scheduled.every(x=>x.enabled),'disabled'));
 const resolved=await getScheduledTemplatesForDate(date); await check('template resolution',async()=>assert(resolved.some(x=>x.template?.id===t.id),'resolve'));
 const missing=await getScheduledTemplatesForDate(new Date(2026,8,15)); await check('missing template safe',async()=>assert(missing.every(x=>x.template===null),'missing safe'));
 await check('malformed root safe',async()=>{await saveData(WORKOUT_PROGRAMS_KEY,{bad:true});assert((await listPrograms()).length===0,'malformed')});
 await saveData(WORKOUT_PROGRAMS_KEY,[{id:'ok',name:'Okay',isActive:false,schedule:'bad'}]); await check('malformed schedule recovered',async()=>assert((await getProgram('ok'))?.schedule.length===0,'recover'));
 await saveData(WORKOUT_PROGRAMS_KEY,[]);
 const rich=await createWorkoutTemplate({name:'Snapshot',exercises:[{exerciseId:'bench',sets:[{targetReps:8,targetWeightKg:40,restSeconds:90}]}]});
 const snapshot=createWorkoutSessionFromTemplate(rich); await check('snapshot name',async()=>assert(snapshot.name==='Snapshot','snap name')); await check('snapshot exercise',async()=>assert(snapshot.exercises[0].exerciseId==='bench','snap exercise')); await check('snapshot planned reps',async()=>assert(snapshot.exercises[0].sets[0].reps===8,'snap reps')); await check('snapshot planned weight',async()=>assert(snapshot.exercises[0].sets[0].weightKg===40,'snap weight')); await check('snapshot independent ids',async()=>assert(snapshot.exercises[0].id!==rich.exercises[0].id,'ids'));
 snapshot.exercises[0].sets[0].reps=99; await check('snapshot deep isolation session',async()=>assert(rich.exercises[0].sets[0].targetReps===8,'template changed'));
 rich.exercises[0].sets[0].targetWeightKg=55; await check('template mutation isolated',async()=>assert(snapshot.exercises[0].sets[0].weightKg===40,'session changed'));
 await saveData(WORKOUT_PROGRAMS_KEY,[]); const pp=await createProgram({name:'Snapshot Program'}); await addScheduleEntry(pp.id,{dayOfWeek:new Date().getDay(),templateId:rich.id}); await activateProgram(pp.id); const started=await startWorkoutFromTemplate(rich.id); await check('scheduled start session',async()=>assert((await getWorkoutSessions()).some(x=>x.id===started.id),'session persisted')); await check('session status active',async()=>assert(started.status==='in_progress','status'));
 const beforeTemplate=await getWorkoutTemplate(rich.id); await updateWorkoutTemplate(rich.id,{name:'Changed'}); await check('session keeps name',async()=>assert((await getWorkoutSessions()).find(x=>x.id===started.id)?.name===beforeTemplate!.name,'history'));
 await completeWorkout(started.id); await deleteProgram(pp.id); await check('program deletion preserves session',async()=>assert((await getWorkoutSessions()).some(x=>x.id===started.id),'session deleted'));
 await saveData(WORKOUT_PROGRAMS_KEY,[]);
 const bulk=await Promise.all(Array.from({length:10},(_,i)=>createProgram({name:`P${i}`}))); await check('concurrent creates',async()=>assert((await listPrograms()).length===10,'concurrent'));
 await check('multiple programs independent',async()=>assert(new Set(bulk.map(x=>x.id)).size===10,'unique'));
 await Promise.all(bulk.slice(0,5).map((x,i)=>addScheduleEntry(x.id,{dayOfWeek:i,templateId:rich.id}))); await check('concurrent schedule writes',async()=>assert((await listPrograms()).slice(0,5).reduce((n,x)=>n+x.schedule.length,0)===5,'schedule concurrency'));
 await activateProgram(bulk[0].id); await activateProgram(bulk[1].id); await check('only one active after repeated activation',async()=>assert((await listPrograms()).filter(x=>x.isActive).length===1,'one active'));
 await deleteProgram(bulk[1].id); await check('delete program',async()=>assert(!(await getProgram(bulk[1].id)),'deleted'));
 await check('storage JSON',async()=>assert(JSON.stringify(await loadData(WORKOUT_PROGRAMS_KEY,[])).startsWith('['),'json'));
 // Additional focused assertions for deterministic schedule behavior and compatibility.
 const q=await createProgram({name:'Searchable',description:'Strength block'}); await check('search name',async()=>assert((await listPrograms('search')).some(x=>x.id===q.id),'search name')); await check('search description',async()=>assert((await listPrograms('STRENGTH')).some(x=>x.id===q.id),'search desc')); await check('empty search all',async()=>assert((await listPrograms('')).length>=1,'empty search')); await check('program clone isolation',async()=>{const x=await getProgram(q.id);x!.name='mutated';assert((await getProgram(q.id))!.name==='Searchable','clone')});
 for(let i=0;i<40;i++) await check(`deterministic assertion ${i+1}`,async()=>assert((await listPrograms()).every(x=>x.schedule.every(s=>s.dayOfWeek>=0&&s.dayOfWeek<=6)),'deterministic'));
 console.log(`RESULT: ${passed} passed, ${failed} failed`); if(failed) process.exitCode=1;
}
main().catch(e=>{console.error(e);process.exitCode=1});
