import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,View } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft,Heart,History,Layers,Repeat2,Target,Activity } from 'lucide-react-native';
import { Card } from '@/components/ui/card'; import { Heading } from '@/components/ui/heading'; import { Text } from '@/components/ui/text'; import { Button,ButtonText } from '@/components/ui/button';
import { getRecentFoods,getFavoriteFoods,getMealTemplates,getNutritionDatasetVersion,calculateWeeklyNutritionAdherence,toggleFavoriteFood,type MealTemplate } from '@/services/nutritionAdvanced'; import { getFoodLogs,getFoods } from '@/services/nutrition'; import { getWorkoutHistory } from '@/services/workoutHistory'; import type { FoodItem } from '@/types/nutrition'; import { getTodayDate } from '@/types/nutrition';

export default function AdvancedNutrition(){const router=useRouter();const[recent,setRecent]=useState<FoodItem[]>([]);const[favs,setFavs]=useState<FoodItem[]>([]);const[templates,setTemplates]=useState<MealTemplate[]>([]);const[adherence,setAdherence]=useState<any>(null);const[version,setVersion]=useState<any>(null);const[workoutLink,setWorkoutLink]=useState<{days:number;logged:number;protein:number|null;calories:number|null}>({days:0,logged:0,protein:null,calories:null});const[loading,setLoading]=useState(true);
const load=async()=>{setLoading(true);try{const[a,b,c,d,e,logs,foods,workouts]=await Promise.all([getRecentFoods(),getFavoriteFoods(),getMealTemplates(),calculateWeeklyNutritionAdherence(getTodayDate()),getNutritionDatasetVersion(),getFoodLogs(),getFoods(),getWorkoutHistory()]);setRecent(a);setFavs(b);setTemplates(c);setAdherence(d);setVersion(e);const map=new Map(foods.map(f=>[f.id,f]));const dates=new Set(workouts.workouts.map(w=>(w.completedAt??w.createdAt).slice(0,10)));const totals=new Map<string,{p:number;c:number}>();for(const l of logs){if(!dates.has(l.date))continue;const f=map.get(l.foodId);if(!f)continue;const factor=f.nutrition.basis==='per_serving'?l.quantity/(f.nutrition.servingAmount||1):(l.unit==='g'||l.unit==='ml'?l.quantity/100:l.quantity);const x=totals.get(l.date)??{p:0,c:0};x.p+=f.nutrition.protein*factor;x.c+=f.nutrition.calories*factor;totals.set(l.date,x)}const vals=[...totals.values()];setWorkoutLink({days:dates.size,logged:vals.length,protein:vals.length?vals.reduce((n,x)=>n+x.p,0)/vals.length:null,calories:vals.length?vals.reduce((n,x)=>n+x.c,0)/vals.length:null})}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
if(loading)return <View className="flex-1 items-center justify-center bg-background"><ActivityIndicator/><Text className="mt-3 text-muted-foreground">Loading nutrition intelligence...</Text></View>;
const FoodLine=({food}:{food:FoodItem})=><View className="flex-row items-center justify-between border-b border-border/60 py-2"><View className="flex-1"><Text size="sm">{food.name}</Text><Text size="xs" className="text-muted-foreground">{food.nutrition.calories} kcal A� {food.sourceDetail??food.source}</Text></View><Pressable onPress={async()=>{await toggleFavoriteFood(food.id);await load()}} accessibilityRole="button" accessibilityLabel={`Toggle favorite ${food.name}`}><Heart size={17}/></Pressable></View>;
return <ScrollView className="flex-1 bg-background" contentContainerStyle={{padding:20,paddingTop:56,paddingBottom:40,gap:12}}>
<View className="flex-row items-center gap-3"><Pressable onPress={()=>router.back()} className="h-10 w-10 items-center justify-center rounded-2xl bg-muted"><ArrowLeft size={20}/></Pressable><View><Text size="xs" className="text-muted-foreground">Nutrition</Text><Heading size="xl">Nutrition Intelligence</Heading></View></View>
<Card className="p-4 gap-2"><View className="flex-row items-center gap-2"><Target size={18}/><Heading size="sm">Weekly adherence</Heading></View><Text size="sm">{adherence?.loggedDays??0}/7 days logged</Text><Text size="xs" className="text-muted-foreground">{adherence?.averageCalories==null?'Calorie average unavailable.':`Average ${Math.round(adherence.averageCalories)} kcal A� protein ${Math.round(adherence.averageProtein??0)} g`}</Text></Card>
<Card className="p-4 gap-2"><View className="flex-row items-center gap-2"><Activity size={18}/><Heading size="sm">Nutrition on workout days</Heading></View><Text size="sm">{workoutLink.logged}/{workoutLink.days} workout days had nutrition logs.</Text><Text size="xs" className="text-muted-foreground">{workoutLink.protein==null?'Protein average unavailable.':`Average logged protein on workout days: ${Math.round(workoutLink.protein)} g; calories: ${Math.round(workoutLink.calories??0)} kcal.`}</Text><Text size="xs" className="text-muted-foreground">This describes logged data and does not establish that nutrition caused training outcomes.</Text></Card>
<Card className="p-4 gap-2"><View className="flex-row items-center gap-2"><History size={18}/><Heading size="sm">Recent foods</Heading></View>{recent.length?recent.slice(0,10).map(f=><FoodLine key={f.id} food={f}/>):<Text size="sm" className="text-muted-foreground">Foods become recent after logging.</Text>}</Card>
<Card className="p-4 gap-2"><View className="flex-row items-center gap-2"><Heart size={18}/><Heading size="sm">Favourite foods</Heading></View>{favs.length?favs.slice(0,10).map(f=><FoodLine key={f.id} food={f}/>):<Text size="sm" className="text-muted-foreground">Tap the heart beside a food to save it.</Text>}</Card>
<Card className="p-4 gap-2"><View className="flex-row items-center gap-2"><Layers size={18}/><Heading size="sm">Meal templates</Heading></View><Text size="sm">{templates.length} reusable meal templates</Text><Button variant="outline" onPress={()=>router.push('/nutrition/meal-templates' as never)}><ButtonText>Manage meal templates</ButtonText></Button></Card>
<Card className="p-4 gap-2"><View className="flex-row items-center gap-2"><Repeat2 size={18}/><Heading size="sm">Fast repeat</Heading></View><Text size="xs" className="text-muted-foreground">Recent foods, favourites, serving presets and repeat-meal actions reduce repeated entry.</Text></Card>
<Card className="p-4 gap-2"><Heading size="sm">Dataset provenance</Heading><Text size="xs" className="text-muted-foreground">{version?`Version ${version.version} A� ${version.foodCount} foods A� source ${version.source} A� imported ${new Date(version.importedAt).toLocaleDateString()}`:'Dataset version has not been recorded yet.'}</Text></Card>
<Button variant="outline" onPress={()=>router.push('/nutrition/analytics' as never)}><ButtonText>Open nutrition analytics</ButtonText></Button>
</ScrollView>}