import { useEffect,useState } from 'react';
import { ActivityIndicator,Pressable,ScrollView,View } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft,Dumbbell,Layers,Timer,Trophy } from 'lucide-react-native';
import { Card } from '@/components/ui/card'; import { Heading } from '@/components/ui/heading'; import { Text } from '@/components/ui/text'; import { Button,ButtonText } from '@/components/ui/button';
import { getWorkoutAdvancedAnalytics,getWorkoutBlocks,getExerciseGroupings,saveWorkoutBlocks,saveExerciseGroupings,type WorkoutAdvancedAnalytics,type WorkoutBlock,type ExerciseGrouping } from '@/services/workoutAdvanced'; import { getWorkoutHistory } from '@/services/workoutHistory';

export default function TrainingToolkit(){const router=useRouter();const[data,setData]=useState<WorkoutAdvancedAnalytics|null>(null);const[workoutId,setWorkoutId]=useState<string|null>(null);const[blocks,setBlocks]=useState<WorkoutBlock[]>([]);const[groupings,setGroupings]=useState<ExerciseGrouping[]>([]);const[loading,setLoading]=useState(true);
const load=async()=>{setLoading(true);try{const[a,h]=await Promise.all([getWorkoutAdvancedAnalytics(90),getWorkoutHistory()]);setData(a);const w=h.workouts[0];if(w){setWorkoutId(w.id);setBlocks(await getWorkoutBlocks(w.id));setGroupings(await getExerciseGroupings(w.id));}}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
const addBlock=async(type:'warmup'|'cooldown')=>{if(!workoutId)return;const next=[...blocks,{id:Date.now().toString(),type,label:type==='warmup'?'Warm-up':'Cool-down',durationMinutes:type==='warmup'?8:5,exerciseIds:[]}];setBlocks(next);await saveWorkoutBlocks(workoutId,next)};
const addGrouping=async(mode:'superset'|'circuit')=>{if(!workoutId)return;const h=await getWorkoutHistory();const w=h.workouts.find(x=>x.id===workoutId);const ids=w?.exercises.slice(0,mode==='superset'?2:3).map(x=>x.exerciseId)??[];if(ids.length<2)return;const next=[...groupings,...ids.map((exerciseId,i)=>({exerciseId,groupId:`${mode}-${Date.now()}`,mode} as ExerciseGrouping))];setGroupings(next);await saveExerciseGroupings(workoutId,next)};
if(loading)return <View className="flex-1 items-center justify-center bg-background"><ActivityIndicator/><Text className="mt-3 text-muted-foreground">Loading training toolkit...</Text></View>;
return <ScrollView className="flex-1 bg-background" contentContainerStyle={{padding:20,paddingTop:56,paddingBottom:40,gap:12}}>
<View className="flex-row items-center gap-3"><Pressable onPress={()=>router.back()} className="h-10 w-10 items-center justify-center rounded-2xl bg-muted"><ArrowLeft size={20}/></Pressable><View><Text size="xs" className="text-muted-foreground">Health</Text><Heading size="xl">Training Toolkit</Heading></View></View>
<Card className="p-4 gap-3"><View className="flex-row items-center gap-2"><Trophy size={18}/><Heading size="sm">Adherence analytics</Heading></View><Text size="sm">{data?.adherence.completedWorkouts??0} completed workouts in 90 days</Text><Text size="xs" className="text-muted-foreground">{data?.adherence.activeDays??0} active days A� longest gap {data?.adherence.longestGapDays??0} days</Text></Card>
<Card className="p-4 gap-3"><View className="flex-row items-center gap-2"><Dumbbell size={18}/><Heading size="sm">Muscle balance</Heading></View>{data?.muscleBalance.slice(0,12).map(x=><View key={x.muscle} className="flex-row justify-between"><Text size="sm">{x.muscle}</Text><Text size="xs" className="text-muted-foreground">{x.sets} sets A� {x.sharePercent}%</Text></View>)}</Card>
<Card className="p-4 gap-3"><View className="flex-row items-center gap-2"><Timer size={18}/><Heading size="sm">Warm-up / cool-down blocks</Heading></View><Text size="xs" className="text-muted-foreground">Separate preparation and recovery blocks keep working-set volume clean.</Text>{blocks.map(b=><View key={b.id} className="rounded-xl bg-muted p-3"><Text size="sm" className="font-semibold">{b.label}</Text><Text size="xs" className="text-muted-foreground">{b.durationMinutes??0} minutes A� {b.exerciseIds.length} exercises</Text></View>)}<View className="flex-row gap-2"><Button variant="outline" className="flex-1" onPress={()=>void addBlock('warmup')}><ButtonText>Add warm-up</ButtonText></Button><Button variant="outline" className="flex-1" onPress={()=>void addBlock('cooldown')}><ButtonText>Add cool-down</ButtonText></Button></View></Card>
<Card className="p-4 gap-3"><View className="flex-row items-center gap-2"><Layers size={18}/><Heading size="sm">Supersets / circuits</Heading></View><Text size="xs" className="text-muted-foreground">Groupings are stored independently so progression and volume remain attributable to each exercise.</Text>{groupings.length?<Text size="sm">{groupings.filter(x=>x.mode==='superset').length} superset assignments A� {groupings.filter(x=>x.mode==='circuit').length} circuit assignments</Text>:<Text size="sm">No groups configured.</Text>}<View className="flex-row gap-2"><Button variant="outline" className="flex-1" onPress={()=>void addGrouping('superset')}><ButtonText>Group first 2</ButtonText></Button><Button variant="outline" className="flex-1" onPress={()=>void addGrouping('circuit')}><ButtonText>Group first 3</ButtonText></Button></View></Card>
<Button variant="outline" onPress={()=>router.push('/health/workout-progression' as never)}><ButtonText>Progression, RPE/RIR and PRs</ButtonText></Button><Button variant="outline" onPress={()=>router.push('/health/workout-insights' as never)}><ButtonText>Volume, balance and adherence</ButtonText></Button>
</ScrollView>}