import { useCallback, useEffect, useState } from 'react';
import { ScrollView, View, TextInput } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { ArrowDown, ArrowUp, Plus, Trash2 } from 'lucide-react-native';
import { Card } from '@/components/ui/card'; import { Heading } from '@/components/ui/heading'; import { Text } from '@/components/ui/text'; import { Button, ButtonText } from '@/components/ui/button';
import { useWorkoutPrograms } from '@/hooks/useWorkoutPrograms';
import type { WorkoutProgram, WorkoutTemplate } from '@/types/workout';
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export default function WorkoutProgramEditorScreen(){const {id}=useLocalSearchParams<{id:string}>();const {getProgram,getTemplates,updateProgram,addScheduleEntry,reorderScheduleEntries,updateScheduleEntry,removeScheduleEntry,setProgramActive}=useWorkoutPrograms();const [p,setP]=useState<WorkoutProgram|null>(null);const [templates,setTemplates]=useState<WorkoutTemplate[]>([]);const [name,setName]=useState('');const [description,setDescription]=useState('');
 const load=useCallback(async()=>{if(!id)return;const [x,t]=await Promise.all([getProgram(id),getTemplates()]);if(x){setP(x);setName(x.name);setDescription(x.description??'')}setTemplates(t)},[id,getProgram,getTemplates]);useEffect(()=>{ // eslint-disable-next-line react-hooks/set-state-in-effect
 void load()},[load]);
 const save=async()=>{if(!p)return;setP(await updateProgram(p.id,{name,description}));};
 const add=async(day:number)=>{if(!p||!templates.length)return;const t=templates[0];setP(await addScheduleEntry(p.id,{dayOfWeek:day,templateId:t.id}))};
 if(!p)return <View className="flex-1 bg-background items-center justify-center"><Text>Program not found.</Text></View>;
 return <View className="flex-1 bg-background"><ScrollView contentContainerStyle={{padding:20,paddingBottom:40}}><View className="gap-4"><Heading size="xl" className="font-bold">Program Editor</Heading><TextInput value={name} onChangeText={setName} placeholder="Program name"/><TextInput value={description} onChangeText={setDescription} placeholder="Description"/><View className="flex-row gap-2"><Button onPress={()=>void save()}><ButtonText>Save</ButtonText></Button><Button variant="outline" onPress={()=>void setProgramActive(p.id,!p.isActive).then(load)}><ButtonText>{p.isActive?'Deactivate':'Activate'}</ButtonText></Button></View><Heading size="md" className="font-bold mt-2">Weekly Schedule</Heading>{days.map((day,di)=><Card key={day} className="p-4 rounded-3xl border border-border gap-3"><View className="flex-row items-center justify-between"><Heading size="sm" className="font-bold">{day}</Heading><Button size="sm" variant="outline" onPress={()=>void add(di)}><Plus size={16}/><ButtonText>Add</ButtonText></Button></View>{p.schedule.filter(e=>e.dayOfWeek===di).sort((a,b)=>a.order-b.order).map(e=><View key={e.id} className="flex-row items-center gap-2"><Text className="flex-1">{templates.find(t=>t.id===e.templateId)?.name??`Missing template (${e.templateId})`}</Text><Button size="sm" variant="outline" onPress={()=>void reorderScheduleEntries(p.id,e.id,-1).then(setP)}><ArrowUp size={14}/></Button><Button size="sm" variant="outline" onPress={()=>void reorderScheduleEntries(p.id,e.id,1).then(setP)}><ArrowDown size={14}/></Button><Button size="sm" variant="outline" onPress={()=>void updateScheduleEntry(p.id,e.id,{enabled:!e.enabled}).then(setP)}><ButtonText>{e.enabled?'Disable':'Enable'}</ButtonText></Button><Button size="sm" variant="outline" onPress={()=>void removeScheduleEntry(p.id,e.id).then(setP)}><Trash2 size={14}/></Button></View>)}</Card>)}</View></ScrollView></View>}
